# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "d6450eb43940fdb3c03b828a376d552a"
name = "YONOOX"
application_url = "https://yonoox.vercel.app"
embedded = true

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2026-01"

[[webhooks.subscriptions]]
topics = ["customers/data_request"]
uri = "/webhooks/customers/data_request"

[[webhooks.subscriptions]]
topics = ["customers/redact"]
uri = "/webhooks/customers/redact"

[[webhooks.subscriptions]]
topics = ["shop/redact"]
uri = "/webhooks/shop/redact"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://yonoox.vercel.app/auth/callback",
  "https://yonoox.vercel.app/auth/shopify/callback"
]
